# Generated by Django 5.0.4 on 2024-04-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_appusermodel_liked_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusermodel',
            name='calories_burnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appusermodel',
            name='hrs_spend',
            field=models.IntegerField(default=0),
        ),
    ]
